### ISSUE TITLE
在 Greasy Fork 发布的可能解决方案？

### ISSUE THREAD

**Issue by E011011101001** [action-hong/handle-solution#1]
根据 [Greasy Fork's policy on external scripts](https://greasyfork.org/en/help/external-scripts)，若要引用 JsDelivr 上托管的 npm 包，符合条件的 URL 格式只有 `^(https?:)?\/\/cdn\.jsdelivr\.net\/npm\/.+@[0-9\.]+.*`，因此显然目前 `index.js` 文件中的 `cnchar` 包无法通过 Greasy Fork 的正则检验。不过如果把 7、8 行对 `cnchar` 和 `cnchar-idoms` 的引入替换为下面的 URL 以符合要求是不是就能成功发布了呢？

```
// @require      https://cdn.jsdelivr.net/npm/cnchar@3.0.5/cnchar.min.js
// @require      https://cdn.jsdelivr.net/npm/cnchar-idiom@3.0.5/cnchar.idiom.min.js
```

因为没有验证所以没有提 Pull Request，如果您有时间或许可以尝试下？

**Comment by action-hong** [comment]
感谢，周末试看看

**Comment by action-hong** [comment]
@E011011101001 

感谢反馈，这样应该是可以的，

不过早上想了下直接把所有成语信息硬编码到代码更便捷（反正脚本都是事先下载到本地的）

[已上传](https://greasyfork.org/zh-CN/scripts/440953-%E6%B1%89%E5%85%9C)
